### ISSUE TITLE
Backup wrong order

### ISSUE THREAD

**Issue by s-balint** [CHR15cs/CS2-Practice-Plugin#18]
Another problem I saw was this: The order of the backup is wrong it came like this 

[!1] 01
[!2] 03
[!3] 02
[!4] 04
[!5] 05

I dont know whats the original idea for the 01, 02, 03, but if you could do it like it shows the score or smth, like
 [!2] 1-1 means second round score: 1-1, or smth like this

or just do .backup last and it would auto backup last round

https://gyazo.com/d3d5eb68afb0452a2d71a7d067738b96

Sorry for spamming with theese, just some issues came up after testing, haha

**Comment by CHR15cs** [comment]
Thank you for giving me this helpfull feedback, let me know anything you find. (or if you want some other features added!)
The names (01 02 03 etc) are just taken from name of the backupfiles generated by valve.
I assume they represent the total rounds played.

I like the idea, I will add this to my todo list :)
