### ISSUE TITLE
From .warmup you cant do anything

### ISSUE THREAD

**Issue by s-balint** [CHR15cs/CS2-Practice-Plugin#20]
If match is live and I want to go back to warmup phase I type .warmup, but from there I cant ready I cant do anything. I can only go .pracc and go back to .match from that to start match.

I think .warmup should have the function to start .match, like this I dont see any point in having that. 

Also I think there should only be 1 warmup config in the files.

**Comment by s-balint** [comment]
I think .warmup should put you back to the ready up phase, and if both teams ready up match is live.

**Comment by CHR15cs** [comment]
Should it start from 0-0 or load the latest backup?

**Comment by s-balint** [comment]
0-0, like a new match
