### ISSUE TITLE
In Practice Mode Let Players Spawn With Grenades

### ISSUE THREAD

**Issue by abstio** [CHR15cs/CS2-Practice-Plugin#24]
As a quality of life change you could let players spawn with grenades in practice mode, instead of having to buy them every time.
For this you can use following convars:
`mp_ct_default_grenades "weapon_incgrenade weapon_hegrenade weapon_smokegrenade weapon_flashbang weapon_decoy"`
`mp_t_default_grenades "weapon_molotov weapon_hegrenade weapon_smokegrenade weapon_flashbang weapon_decoy"`
No Idea if the decoy grenade is necessary, just wanted to include it here. Remove `weapon_decoy` to not let players spawn with decoys.

To revert this for scrims/pugs/live matches just add `mp_ct_default_grenades ""` and `mp_t_default_grenades ""` to `undo_pracc.cfg` or `5on5.cfg`. I'm unsure if you have to set them to `""` or `0` as Valve themselves use `""` for similar convars in `cfg/gamemode_competitive.cfg`, but [this reference](https://totalcsgo.com/commands/mptdefaultgrenades) uses `0`, just to let you know.

You could also disable grenade dropping (`mp_death_drop_grenade 0`) with this change to keep the map a bit cleaner after many respawns as all players will spawn with grenades anyway

**Comment by CHR15cs** [comment]
Thanks for the great input
I will make sure to add this in the next release
