### ISSUE TITLE
Spawn .bot (player stuck) / extra bot will not spawn*

### ISSUE THREAD

**Issue by mrc4tt** [CHR15cs/CS2-Practice-Plugin#42]
Hi,

If I do `.bot` from `.pracc`, the player will be stuck and unable to move at all.

And, if I try to add 1 more `.bot` it says `Cannot add bots, the team is full! Use .nobots to remove the current bots.`
![image](https://github.com/CHR15cs/CS2-Practice-Plugin/assets/5301047/ae4e50fb-8a7f-4454-891c-5177e46c5c1a)

**Comment by CHR15cs** [comment]
Use console command "noclip" in order to move freely
"mp_limitteams 0" should help to add more bots
You can edit the pracc.cfg and add this command or type ".rcon mp_limitteams 0" in the chat
