### ISSUE TITLE
Feature: list tags

### ISSUE THREAD

**Issue by naofireblade** [CHR15cs/CS2-Practice-Plugin#44]
Hi, I really appreciate your work on this plugin. Could you implement a command to list all available nade tags?

**Comment by CHR15cs** [comment]
Yes
Should be done by tomorrow.
Thank you for the great feedback,

**Comment by CHR15cs** [comment]
Would this meet your expectation?
![showtags](https://github.com/CHR15cs/CS2-Practice-Plugin/assets/59683453/3103295c-0bd5-4683-8340-df5bc57b44f9)

The command would show you depending on your selected nade menu (global or personalized) every available tag

**Comment by naofireblade** [comment]
Yes! That looks great. Thank u very much.

**Comment by CHR15cs** [comment]
No problem, please continue providing me such helpfull feedback :)
There are some other enhancements I want to finish before releasing, but will be uploaded tomorrow

**Comment by CHR15cs** [comment]
implemented in https://github.com/CHR15cs/CS2-Practice-Plugin/commit/b7ce25e6eed31517f00108b5bf5826cf2450d13a 
release will be uploaded shortly
