### ISSUE TITLE
Apply nade manipulations to last used nade

### ISSUE THREAD

**Issue by naofireblade** [CHR15cs/CS2-Practice-Plugin#45]
A .delete command to remove the last loaded nade would be useful.

**Comment by CHR15cs** [comment]
Currently the .delete command requires a parameter with the id of the nade you want to delete. (use .nades to see the ID)
I can implement that it if no number is passed the last saved grenade will be deleted

**Comment by CHR15cs** [comment]
My bad, that wiki isnt up2date yet.

In the update planned for today, there will be a .editnade <id> command.
This way you can select a grenade and edit it with .desc .rename etc. and no extra parameter is required.
In the last version I just totally forgott about it.

If you think its more convenient to just edit the last loaded grenade, that would be fine for me as well.

**Comment by naofireblade** [comment]
I think it's more convenient yes. And i can imagine many users come from the cs go practice plugin and assume the same behavior.

**Comment by CHR15cs** [comment]
Implemented in commit https://github.com/CHR15cs/CS2-Practice-Plugin/commit/b7ce25e6eed31517f00108b5bf5826cf2450d13a
Release should be uploaded shortly :)

.delete without parameters will delete the last used or saved nade
to delete a specific nade use .delete <id>
