### ISSUE TITLE
Would like to see a prefire mode added.

### ISSUE THREAD

**Issue by Jaakkogithub** [CHR15cs/CS2-Practice-Plugin#47]
If possible the addition of prefire mode would be greatly appreciated due to no yprac maps yet available. Something similar to this https://www.youtube.com/watch?v=wRnFTs0PK9E. Where you could add your own bots and save it.

**Comment by CHR15cs** [comment]
Hey,
prefire mode is something I already started working on.
Will continue working on it as soon as I atleast have a basic version of bot mimic working, this should not take too long anymore.

The plan is to provide basic routes for all competitiv maps and the possibility to create your own.
Also something I want to to is a tag-team mode where you can play this together with someone else, but first of all I want to provide the basic features.
