### ISSUE TITLE
Plugins not running

### ISSUE THREAD

**Issue by BigSaVo** [CHR15cs/CS2-Practice-Plugin#52]
Today there was a server update of Cs2. Unfortunately the plugin apparently no longer works. Does anyone have an idea how I can get the plugin to work again? I have Metamod mmsource-2.0.0-git1280-linux and counterstrikesharp-build-161-linux-b9ca63a.

Despite the current versions, the commands in the chat do not work.

Can anyone help me?

**Comment by CHR15cs** [comment]
Do  commands like  'css_plugins list' (server console) etc work?

**Comment by BigSaVo** [comment]
No, that doesn't work either. Although CounterStrikeSharp released a new version 4 hours ago.

**Comment by nuxencs** [comment]
CounterStrikeSharp isn't updated for the latest version yet
the update from 11am gmt+1 is not related to the cs2 update

**Comment by mrc4tt** [comment]
You need to update gamedata.json to counterstrikesharp ^

**Comment by CHR15cs** [comment]
Updated the last release with the new metamod and cssharp including the gamedata
I only tested basic stuff on linux and it worked for now
If you encouter any other issues, please let me know

**Comment by BigSaVo** [comment]
Oh man, Ich habe keine Ahnung mehr was ich machen soll. Ich habe auch einen Linux Server und habe jetzt Metamod 2.0.0-git1282 drauf. Dann die counterstrikesharp-build-163-linux-12c6f4d version und das Plugin von dir. Trotzdem läuft bei mir nichts.

Das steht bei mir in der gameinfo.gi:

FileSystem
	{
		SearchPaths
		{
			Game_LowViolence	csgo_lv // Perfect World content override

			Game    csgo/addons/metamod
			Game	csgo
			Game	csgo_imported
			Game	csgo_core
			Game	core

			Mod		csgo
			Mod		csgo_imported
			Mod		csgo_core

			AddonRoot			csgo_addons

			LayeredGameRoot		"../game_otherplatforms/etc" [$MOBILE || $ETC_TEXTURES] //Some platforms do not support DXT compression. ETC is a well-supported alternative.
			LayeredGameRoot		"../game_otherplatforms/low_bitrate" [$MOBILE]

Habe ich vielleicht irgendetwas vergessen? Weiß gerade nicht weiter. Bis zu den Server update lief alles ohne Probleme.

**Comment by CHR15cs** [comment]
Hast du das Linux Release von hier von vorhin runtergeladen?
https://github.com/CHR15cs/CS2-Practice-Plugin/releases/tag/v1.0.0.1
Habe da ein complete package hochgeladen welches die benötigten Sachen beinhaltet

**Comment by BigSaVo** [comment]
Ja ich habe die aktuelle Version von dir runtergeladen. Aber es hängt wohl momentan das auf dem Server Metamod oder CCS nicht läuft.

**Comment by CHR15cs** [comment]
Kannst mal schauen ob "meta list" oder "css_plugins list" funktioniert
Die Gameinfo datei sieht eigtl. gut aus

**Comment by BigSaVo** [comment]
Hi ich habe gestern noch ein anderes Plugin getestet das wäre MatchZy. Das lief dann ohne Probleme.
Es gab ja heute wieder Server-Updates werde später es nochmal neu probieren. Und dir die Infos zukommen lassen. Würde nämlich echt gerne dein Plugin mal testen.

**Comment by BigSaVo** [comment]
So nach den ganzen Updates wird dein Plugin erkannt.

![grafik](https://github.com/CHR15cs/CS2-Practice-Plugin/assets/77449760/20f41ed7-b8cf-4f84-b41c-9a04bbec157c)

Jetzt frage ich mir nuch warum er mich als Admin nicht erkennt???

Unter folgendem Pfad gibt es die admins.jason: game/csgo/addons/counterstrikesharp/configs

Dorst habe ich mich als Admin eingetragen:

{
  "BigSaVo": {
    "identity": "765611979870483033",
    "flags": [
      "@css/root"
    ]
  },
  
  Unter dem Plaugin MatchZy funktionert es. Muss ich bei dien Plugin etwas anderes eingeben?

**Comment by BigSaVo** [comment]
Hey, danke dir für deine Hilfe. Das Plugin läuft und ich werde das jetzt mit dem Team testen. Klingt soweit alles ganz gut was das Plugin können soll.
