### ISSUE TITLE
Request: Add a command to save last nade

### ISSUE THREAD

**Issue by willjsaint** [CHR15cs/CS2-Practice-Plugin#8]
I always found it a little unergonomic to always need to use .back to before saving a grenade. If there was something like .savelast then you could throw a grenade and save it without needing to go back to the lineup.

**Comment by CHR15cs** [comment]
Sounds like a great idea, I`ll have a look at it.

**Comment by CHR15cs** [comment]
Implemented the feature in [this commit](https://github.com/CHR15cs/CS2-Practice-Plugin/commit/e15c629be323ce91cd803396aa34727292cfab94) <br> Will ship a new rleease v0.9.0.1 soon.<br>Please be aware that there might be breaking changes since I refactored game event handling.
